# fly.toml file generated for stargazers-api on 2022-12-03T17:46:22+01:00

app = "stargazers-worker"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  [build.args]
    NODE_VERSION = "14"
    PHP_VERSION = "8.1"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[processes]
  app = "php artisan horizon"
